CREATE TABLE tasks (
    id                        SERIAL PRIMARY KEY,
    title                     VARCHAR(255),
    description               VARCHAR(255),
    assigned_to               VARCHAR(255),
    state                     VARCHAR(50),
    first_name                VARCHAR(255),
    last_name                 VARCHAR(255),
    birth_date                VARCHAR(255),
    email                     VARCHAR(255),
    postal_code               VARCHAR(20),
    city                      VARCHAR(255),
    regulatory_compliance_check VARCHAR(255),
    contract_compliance       VARCHAR(255),
    task_creator              VARCHAR(255),
    task_responsible          VARCHAR(255),
    comments                  VARCHAR(255),
    priority                  VARCHAR(50),
    credit_card               VARCHAR(3),
    estimant_origine          VARCHAR(255),
    project                   VARCHAR(255),
    created_at                VARCHAR(255),
    updated_at                VARCHAR(255)
);
